aliases = [
    ['Theresia Weber', 'Theresia', 'Weber-Gachnang'],
    ['Silvia Seiz', 'Silvia', 'Seiz-Gut'],
    ['Benno Scherrer Moser', 'Benno', 'Scherrer'],
    ['Regula Kaeser', 'Regula', 'Kaeser-Stöckli'],
    ['Markus Späth', 'Markus', 'Späth-Walter'],
    ['Benjamin Schwarzenbach', 'Beni', 'Schwarzenbach'],
    ['Hans-Ueli Züllig', 'Hansueli', 'Züllig'],
    ['Karin Maeder', 'Karin', 'Maeder-Zuberbühler'],
    ['Sabine Wettstein', 'Sabine', 'Wettstein-Studer'],
    ['Corinne Thomet', 'Corinne', 'Thomet-Bürki'],
    ['Martin Farner', 'Martin', 'Farner-Brandenberger'],
    ['Katharina Kull', 'Katharina', 'Kull-Benz'],
    ['Max Homberger', 'Max Robert' ,'Homberger'],
    ['Renate Büchi', 'Renate', 'Büchi-Wild'],
    ['Jakob Scheebeli', 'Jakob', 'Schneebeli'],
    ['Judith Stofer', 'Judith Anna', 'Stofer'],
    ['Karin Egli', 'Karin', 'Egli-Zimmermann'],
    ['Heidi Bucher', 'Heidi', 'Bucher-Steinegger'],
    ['Catherine Heuberger', 'Catherine', 'Heuberger Golta'],
    ['Ursula Moor', 'Ursula', 'Moor-Schwarz'],
    ['Jean-Philipp Pinto', 'Jean-Philippe', 'Pinto'],
    ['Ruth Frei', 'Ruth', 'Frei-Baumann'],
    ['Olivier Hofmann', 'Olivier Moïse', 'Hofmann'],
    ['Hans Wiesner', 'Hans W.', 'Wiesner'],
    ['Philippe Kutter', 'Philipp', 'Kutter'],
    ['Sabine Sieber', 'Sabine', 'Sieber Hirschi'],
    ['Beatrix Frei', 'Beatrix' ,'Frey-Eigenmann'],
    ['Raphael Steiner', 'Rafael', 'Steiner'],
    ['Hansueli Vogt', 'Hans-Ueli', 'Vogt'],
    ['Sylvie Fee Matter', 'Sylvie', 'Matter'],
    ['Cäcilia Hänni', 'Cäcilia', 'Hänni-Etter'],
    ['Kaspar Büttikofer', 'Kaspar', 'Bütikofer'],
    ['Sonja Rueff', 'Sonja', 'Rueff-Frenkel'],
    ['Silvie Matter', 'Sylvie', 'Matter'],
    ['Bettina Balmer', 'Bettina', 'Balmer-Schiltknecht'],
    ['Claudia Wyssen', 'Claudia', 'Frei-Wyssen'],
    ['Barbara Franzen', 'Ann Barbara', 'Franzen'],
    ['Birgit Tognella', 'Birgit', 'Tognella-Geertsen'],
    ['Michèle Dünki', 'Michèle', 'Dünki-Bättig'],
    ['Markus Schaff', 'Markus', 'Schaaf'],
    ['Mark Wisskirchen', 'Mark Anthony', 'Wisskirchen'],
    ['Priska Koller', 'Prisca', 'Koller'],
    ['Hans-Heinrich Raths', 'Hans Heinrich', 'Raths'],
    ['Rita Maria Marty', 'Maria Rita', 'Marty'],
    ['David Galeuchet', 'David John', 'Galeuchet'],
    ['Karin Thoma Fehr', 'Karin', 'Fehr Thoma'],
    ['Ester Meier', 'Esther', 'Meier'],
    ['Hans-Peter Hugentobler', 'Hanspeter', 'Hugentobler'],
    ['Katrin Cometta', 'Katrin', 'Cometta-Müller'],
    ['Nicola Sigrist', 'Nicola', 'Siegrist'],
    ['Qëndresa Sadriu', 'Qëndresa (Qëni)', 'Sadriu'],
    ['Martin Neukomm', 'Martin', 'Neukom'],
    ['Theres Agosti', 'Theres', 'Agosti Monn'],
    ['These Agosti', 'Theres', 'Agosti Monn'],
    ['Roland Alder', 'Ronald', 'Alder'],
    ['Beat Mohnhart', 'Beat', 'Monhart'],
    ['Marc Anthony Wisskirchen', 'Mark Anthony', 'Wisskirchen'],
    ['Ariane Moser', 'Arianne', 'Moser-Schäfer'],
    ['Beatrix Frey-Eigenmann', 'Beatrix', 'Frey'],
    ['Benno Scherer', 'Benno', 'Scherrer Moser'],
    ['Harry Brandenberger', 'Harry Robert', 'Brandenberger'],
    ['Gantner Alex', 'Alex', 'Gantner'],
    ['Cristina Wyss-Cortellini', 'Cristina', 'Cortellini'],
    ['Gehrig Sonja', 'Sonja', 'Gehrig Schmidt'],
    ['Andreas Halser', 'Andreas', 'Hasler'],
    ['Jasmine Pokerschnig', 'Jasmin', 'Pokerschnig'],
    ['Anthony Wisskirchen', 'Mark Anthony', 'Wisskirchen'],
    ['Carola Etter', 'Carola', 'Etter-Gick'],
    ['Christan Schucan', 'Christian', 'Schucan'],
    ['Jürg Kündig', 'Jörg', 'Kündig'],
    ['Edith Häuser', 'Edith', 'Häusler-Michel'],
    ['Edith Häusler', 'Edith', 'Häusler-Michel'],
    ['Franziska Barmetter', 'Franziska', 'Barmettler'],
    ['Stepan Weber', 'Stephan', 'Weber'],
    ['Arianne Moser-Schäfer', 'Arianne', 'Moser'],
    ['Natalie Aeschbacher', 'Nathalie', 'Aeschbacher'],
    ['Fehr Düsel', 'Nina', 'Fehr Düsel'],
    ['Monica Muri Sanesi', 'Monica', 'Sanesi Muri'],
    ['Peter Brunner', 'Hans-Peter', 'Brunner'],
    ['Domenik Ledergeber', 'Domenik', 'Ledergerber'],
    ["Selma L’Orange Seigo", 'Selma', "L'Orange Seigo"],
    ['Markus Schaaf Markus', 'Markus', 'Schaaf'],
    ['Marc Bourgeoise', 'Marc', 'Bourgeois'],
    ['Silva Rigoni', 'Silvia', 'Rigoni'],
    ['Jeanette Büsser', 'Jeannette', 'Büsser'],
    ['Anne-Claude Hensch-Frei', 'Anne-Claude', 'Hensch Frei'],
    ['Hanspeter Amrein', 'Hans-Peter', 'Amrein'],
    ['Jean-Philippe Pinot', 'Jean-Philippe', 'Pinto'],
]